"use client";

// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <link rel="icon" href="/favicon.ico?" />

//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// app/layout.tsx
import Head from "next/head";
import React from "react";

import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const inputRef = React.useRef<HTMLInputElement>(null);

  const onClickAnywhere = () => {
    inputRef.current?.focus();
  };

  return (
    <html lang="en">
      <Head>
        <title>Your App Title</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <link rel="icon" href="/favicon.png?v=2" />
      </Head>

      <body>
        <div id="__next">
          <div
            className="text-light-foreground dark:text-dark-foreground min-w-max text-xs md:min-w-full md:text-base"
            onClick={onClickAnywhere}
          >
            <main className="bg-light-background dark:bg-dark-background w-full h-full p-2">
              {React.cloneElement(children as React.ReactElement, { inputRef })}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
